### PR TITLE
Updated Stops.zip and added support for TimingStatus

### PR DESCRIPTION
**Pull request by pchynoweth**
Thought I should give you the opportunity to take these changes.  For a project I'm working on it's important to know the `TimingStatus` and represent this appropriately in GTFS.  I have added support for this by only setting the `timepoint` column to `1` in stop_times.txt if the `TimingStatus` is "PTP" (Principal Timing Point).  All other `TimingStatus` values are treated as approximate.

### CODE REVIEW

**Comment by linusnorton** [comment]
@pchynoweth thanks for submitting this. I see the Stops.zip has also changed - can you confirm it's in the same format?

**Comment by linusnorton** [comment]
Also, could you please fix the unit tests https://travis-ci.org/planarnetwork/transxchange2gtfs/builds/519893224?utm_source=github_status&utm_medium=notification

**Comment by pchynoweth** [comment]
I've updated the unit tests.

> I see the Stops.zip has also changed - can you confirm it's in the same format?

Yes.  I transformed the latest NaPTAN data to match the existing format because there were some stops I needed that were missing.  For reference here's the head of the file:

```
$ head Stops.csv 
ATCOCode,NaptanCode,CommonName,Street,Indicator,LocalityName,ParentLocalityName,Longitude,Latitude
0100053316,bstjpdm,Broad Walk Shops,,Stop B,Bristol City Centre,Bristol,-2.5876178397,51.4558382170
0100053264,bstmjdp,Alberton Road,Alberton Road,NE-bound,Bristol City Centre,Bristol,-2.5407019785,51.4889912765
0100053308,bstgtgj,Counterslip,Counterslip,SW-bound,Bristol City Centre,Bristol,-2.5876736730,51.4557030625
0100053306,bstapjm,Risdale Road,Risdale Road,SW-bound,Bristol City Centre,Bristol,-2.5878037737,51.4557473682
010000015,bstpgpa,Kings Head Lane,Kings Head Lane,Stop D,Bristol City Centre,Bristol,-2.5878034271,51.4557203950
0100053309,bstawga,Northcote Road,Guthrie Road,NE-bound,Bristol City Centre,Bristol,-2.5875740878,51.4557934781
0100053330,bstdjtd,Ilchester Crescent,Ilchester Crescent,Stop C,Bristol City Centre,Bristol,-2.5876322312,51.4558381448
0100053331,bstdjmg,Ilchester Crescent,Ilchester Crescent,Stop D,Bristol City Centre,Bristol,-2.5876895661,51.4558198741
0100053332,bstdjmw,Brooklyn Road,Brooklyn Road,Stop A,Bristol City Centre,Bristol,-2.5874880853,51.4558208842
```

**Comment by linusnorton** [comment]
@pchynoweth this has been released as version 1.3.0 - thanks again

**Pull request merged**
